# Generated by Django 4.2.4 on 2023-09-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_utc', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[('Inactive', 0), ('Active', 1)])),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_status', to='mainapp.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime_last_hour', models.TimeField()),
                ('uptime_last_day', models.TimeField()),
                ('update_last_week', models.TimeField()),
                ('downtime_last_hour', models.TimeField()),
                ('downtime_last_day', models.TimeField()),
                ('downtime_last_week', models.TimeField()),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mainapp.store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='timezone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mainapp.timezone'),
        ),
        migrations.CreateModel(
            name='BusinessHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField(choices=[('Monday', 0), ('Tuesday', 1), ('Wednesday', 2), ('Thursday', 3), ('Friday', 4), ('Saturday', 5), ('Sunday', 6)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_hours', to='mainapp.store')),
            ],
        ),
    ]
