# Generated by Django 4.2.4 on 2023-09-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_storestatus_timestamp_utc'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereport',
            name='report_id',
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storereport',
            name='report_status',
            field=models.CharField(default='Running', max_length=255),
        ),
        migrations.AlterField(
            model_name='businesshour',
            name='dayOfWeek',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='downtime_last_day',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='downtime_last_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='downtime_last_week',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='update_last_week',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='uptime_last_day',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='uptime_last_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')]),
        ),
    ]
