# Generated by Django 4.2.4 on 2023-09-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_storereport_report_id_storereport_report_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storereport',
            old_name='update_last_week',
            new_name='uptime_last_week',
        ),
    ]
