# Generated by Django 4.2.4 on 2023-09-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_storereport_report_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storereport',
            name='downtime_last_day',
        ),
        migrations.RemoveField(
            model_name='storereport',
            name='downtime_last_hour',
        ),
        migrations.RemoveField(
            model_name='storereport',
            name='downtime_last_week',
        ),
        migrations.RemoveField(
            model_name='storereport',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storereport',
            name='uptime_last_day',
        ),
        migrations.RemoveField(
            model_name='storereport',
            name='uptime_last_hour',
        ),
        migrations.RemoveField(
            model_name='storereport',
            name='uptime_last_week',
        ),
        migrations.AddField(
            model_name='storereport',
            name='report_created',
            field=models.FileField(blank=True, null=True, upload_to='reports'),
        ),
    ]
